### ISSUE TITLE
Can't build this on windows

### ISSUE THREAD

**Issue by TGMM** [mun-lang/lld-rs#3]
When trying to build this I get the error `fatal error C1083: Cannot open include file: 'lld/Common/CommonLinkerContext.h': No such file or directory`.
Where are the headers for lld included? The llvm-config cxx flags only include these two folders `-IC:\llvm\llvm\include -IC:\llvm_build\include`, but I don't see where the `-IC:\llvm\lld\include` flag is (or if it even exists).
For clarification, my llvm source is in the `C:\llvm` folder and my binaries (the built version) is on `C:\llvm_build`. I'm using LLVM 14.0.6.

Thanks in advance for your help.

**Comment by baszalmstra** [comment]
Did you also build LLD itself as part of LLVM? You can find instructions on how to do that here: https://docs.mun-lang.org/dev/02-building-llvm.html . You can also download binaries there that include LLD.

**Comment by TGMM** [comment]
Yes, I have both the lld-link executable as well as the lld headers (which are in the base/lld/include folder). It's just they're not being included with llvm-config. Are your lld headers inside the base/LLVM/include folder?

When I say base I'm referring to the folder that contains the llvm source. In my case that would be C:/llvm.

**Comment by TGMM** [comment]
Many thanks! After downloading the binaries you publish I realized that the lld headers should be inside the C:/llvm-build folder, I probably missed some config in my LLVM build (even though I have lld-link in my binaries folder). I switched to using yours and it works perfectly. Again, thank you very much.

**Comment by Boscop** [comment]
Btw, does `LldFlavor::Coff` also support producing `PE` executables for Windows?

https://github.com/mun-lang/lld-rs/blob/ec1e3349cf1ba0a12808b00bd26a7c5168bb059b/src/lib.rs#L13-L19
